language: c

dist: xenial

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

before_script: 
  - sudo apt-get update
  - sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
  - git clone https://github.com/parvezch/anykernel2.git -b land AnyKernel2
  - git clone https://gitlab.com/anirudhgupta109/gcc-prebuilts -b 8.2.1 gcc8
  - git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 clang
  - git clone https://github.com/parvezch/scripts bs

notifications:
  webhooks:
    urls:
      - https://integrations.bonbotics.io/travis/webhook/6NDHSSgw4PWpF0zMENhTRn8YMN35q9US1zRm4rmEsPU
    on_success: always
    on_failure: always
    on_start: always

script:
  - #!/bin/bash
  - mv bs/kernel.sh kernel.sh
  - bash kernel.sh
